- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /home/touj/test
 
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /home/touj/test/deployment.yaml
      
